# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='animal.proto',
  package='cloud1',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x61nimal.proto\x12\x06\x63loud1\"^\n\x06\x41nimal\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x11\n\tqualities\x18\x02 \x03(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x03 \x03(\t\x12\x0e\n\x06\x63olors\x18\x04 \x03(\t\x12\x11\n\tabilities\x18\x05 \x03(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ANIMAL = _descriptor.Descriptor(
  name='Animal',
  full_name='cloud1.Animal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cloud1.Animal.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qualities', full_name='cloud1.Animal.qualities', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='features', full_name='cloud1.Animal.features', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='colors', full_name='cloud1.Animal.colors', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='abilities', full_name='cloud1.Animal.abilities', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['Animal'] = _ANIMAL

Animal = _reflection.GeneratedProtocolMessageType('Animal', (_message.Message,), dict(
  DESCRIPTOR = _ANIMAL,
  __module__ = 'animal_pb2'
  # @@protoc_insertion_point(class_scope:cloud1.Animal)
  ))
_sym_db.RegisterMessage(Animal)


# @@protoc_insertion_point(module_scope)
