# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: q-and-a.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='q-and-a.proto',
  package='cloud1',
  syntax='proto2',
  serialized_pb=_b('\n\rq-and-a.proto\x12\x06\x63loud1\"*\n\x08Question\x12\x0f\n\x07inquiry\x18\x01 \x02(\t\x12\r\n\x05guess\x18\x02 \x02(\t\"Q\n\x06\x41nswer\x12\x10\n\x08response\x18\x01 \x02(\x08\x12\x11\n\tgame_over\x18\x02 \x01(\x08\x12\"\n\x08question\x18\x03 \x01(\x0b\x32\x10.cloud1.Question')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_QUESTION = _descriptor.Descriptor(
  name='Question',
  full_name='cloud1.Question',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inquiry', full_name='cloud1.Question.inquiry', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='guess', full_name='cloud1.Question.guess', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=67,
)


_ANSWER = _descriptor.Descriptor(
  name='Answer',
  full_name='cloud1.Answer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='cloud1.Answer.response', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_over', full_name='cloud1.Answer.game_over', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='question', full_name='cloud1.Answer.question', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=150,
)

_ANSWER.fields_by_name['question'].message_type = _QUESTION
DESCRIPTOR.message_types_by_name['Question'] = _QUESTION
DESCRIPTOR.message_types_by_name['Answer'] = _ANSWER

Question = _reflection.GeneratedProtocolMessageType('Question', (_message.Message,), dict(
  DESCRIPTOR = _QUESTION,
  __module__ = 'q_and_a_pb2'
  # @@protoc_insertion_point(class_scope:cloud1.Question)
  ))
_sym_db.RegisterMessage(Question)

Answer = _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), dict(
  DESCRIPTOR = _ANSWER,
  __module__ = 'q_and_a_pb2'
  # @@protoc_insertion_point(class_scope:cloud1.Answer)
  ))
_sym_db.RegisterMessage(Answer)


# @@protoc_insertion_point(module_scope)
